[package]
name = "domain"
version = "0.1.0"
edition = "2021"
autolib = false

[dependencies]
serde = { version = "1.0.218", features = ["derive"]}
serde_json = "1.0.139"
uuid = {version="1.14.0", features=[
  "v4",                # Lets you generate random UUIDs
  "serde",
  "fast-rng",          # Use a faster (but still sufficiently random) RNG
  "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]}

[lib]
path = "mod.rs" 
